### PR TITLE
Work with react 0.14-beta*

### PR DESCRIPTION
**Pull request by themouette**

### CODE REVIEW

**Comment by themouette** [comment]
I use it with react 0.14-beta3 and it works well. Thank you for sharing.

My concern is an npm dependency error when used with react@0.14.0-beta3. It aborts the build process and I'm afraid it could result in 2 different versions of react installed.

Any chance this gets merged?

**Comment by Lapple** [comment]
Having read about [prerelease version ranges](https://docs.npmjs.com/misc/semver#prerelease-tags) on npm, I am afraid we would have to specify every possible prerelease version. Maybe we should just go with `*` and fix compatibility problems as they occur, what do you think?

**Comment by Lapple** [comment]
In the meantime, React 0.14 was released and I bumped the version to 5.3.0. Thank you for contribution!

**Comment by themouette** [comment]
great. thx

**Pull request closed without merging**
