### PR TITLE
properly check "search" property value

### PR DESCRIPTION
**Pull request by rutsky**
Fixes react warning when passing "search={false}".

### CODE REVIEW

**Comment by Lapple** [comment]
Thanks, but will the warning go away if you simply pass oneOfType array of func and boolean?

**Comment by rutsky** [comment]
@Lapple, yes, but then it will be possible to pass `true` value, which isn't allowed (and looks like will lead to internal exception).

**Comment by Lapple** [comment]
While technically this is possible, I am not sure if that is a common pitfall. I agree with the PR subject that passing false should not trigger a warning that contradicts with the docs. I just think that having such an extensive error reporting costs too much for the value it brings. Do you agree?

**Comment by rutsky** [comment]
I agree that there is a lot of code for a very small and uncommon bug.

I thought to write oneOfType(boolean, function) initially, but decided that this is technically not correct due to missing `true` value case.

If you want, I can push oneOfType solution.

**Comment by rutsky** [comment]
I pushed in this branch incorrectly checked `isRequired` fix.

I checked that:
- if property is omitted internal search box appears,
- passing `false` disables internal search box,
- passing string leads to React warning (followed by exception which is expected),
- passing `true` leads to exception (which is bug, but it's not worth fixing).

**Comment by Lapple** [comment]
Perfect, thank you!

**Pull request merged**
